package com.mogralabs.mogra.raagdb

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The shipped raag database and its by-swar index.
 *
 * The index is generated by `tools/gen_raagdb.py` and never derived at runtime, so what
 * needs holding is that the two halves agree: every raag must be findable by its own set of
 * swars.
 */
class RaagDbTest {

    private val db = RaagDb.parse(File("src/main/assets/raagdb.json").readText())

    @Test fun `the whole tanarang database is here`() {
        assertEquals(116, db.raags.size)
        assertEquals(listOf("S", "r", "R", "g", "G", "m", "M", "P", "d", "D", "n", "N"),
            db.swarOrder)
    }

    @Test fun `every raag is found by its own swars`() {
        db.raags.forEach { raag ->
            val found = db.matching(raag.swars)
            assertTrue("${raag.name} is not in the index under ${raag.swars}",
                found.any { it.key == raag.key })
        }
    }

    @Test fun `the order the swars are picked in does not matter`() {
        val bhoopali = db.byName("Bhoopali")!!
        assertEquals(db.matching(bhoopali.swars).map { it.key },
            db.matching(bhoopali.swars.reversed()).map { it.key })
    }

    @Test fun `matching is an exact set, not a subset`() {
        val malkauns = db.byName("Malkauns")!!
        assertTrue(db.matching(malkauns.swars).any { it.key == malkauns.key })
        // one swar Malkauns does not have, and it must drop out
        assertTrue(db.matching(malkauns.swars + "P").none { it.key == malkauns.key })
        // a subset must drop out too
        assertTrue(db.matching(malkauns.swars - "n").none { it.key == malkauns.key })
    }

    @Test fun `raags that share a scale come back together`() {
        // Bhoopali and Deshkar are the same five swars, which is the interesting case for
        // this tool -- the answer is a list, not one raag
        val shared = db.matching(listOf("S", "R", "G", "P", "D")).map { it.name }
        assertTrue("expected Bhoopali among $shared", "Bhoopali" in shared)
        assertTrue("expected more than one raag on that scale, got $shared", shared.size > 1)
    }

    @Test fun `an unknown set finds nothing rather than throwing`() {
        assertEquals(emptyList<RaagDb.Raag>(), db.matching(db.swarOrder))
        assertEquals(emptyList<RaagDb.Raag>(), db.matching(emptyList()))
    }

    /** Both are rendered through a lookup, so an unmapped value would show up raw. */
    @Test fun `every thaat and prahar in the data has a translation key`() {
        val thaats = setOf("Bilawal", "Khamaj", "Kafi", "Asawari", "Bhairavi", "Bhairav",
            "Kalyan", "Marwa", "Poorvi", "Todi", "Carnatic Music System", "Not Defined")
        val prahars = setOf("day 1st", "day 2nd", "day 3rd", "day 4th",
            "night 1st", "night 2nd", "night 3rd", "night 4th")
        db.raags.forEach { raag ->
            raag.fields["thaat"]?.forEach {
                assertTrue("${raag.name}: unmapped thaat \"$it\"", it in thaats)
            }
            raag.fields["prahar"]?.forEach {
                assertTrue("${raag.name}: unmapped prahar \"$it\"", it in prahars)
            }
        }
    }

    @Test fun `every raag has the attributes the table shows`() {
        db.raags.forEach { raag ->
            assertNotNull("${raag.name} has no aaroha", raag.fields["aaroha"])
            assertNotNull("${raag.name} has no avaroha", raag.fields["avaroha"])
            assertTrue("${raag.name} has no thaat", raag.fields["thaat"]?.isNotEmpty() == true)
        }
    }
}
