#!/usr/bin/env python3
"""Generate the Android string resources from translation.md.

    python3 tools/gen_strings.py

translation.md is the source of truth for every user-visible string. This reads its tables
and writes values/, values-mr/ and values-hi/ — so a translation is changed by editing the
table and running this, never by editing the XML.

It refuses to write anything if a locale's format specifiers do not match English exactly,
in order. `%1$` with no conversion character sat in the table once and would have crashed
the Result screen at runtime; that check exists because of it.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "translation.md"
LOCALES = (("en", "values"), ("mr", "values-mr"), ("hi", "values-hi"))
COL = {"en": 1, "mr": 2, "hi": 3}

ROW = re.compile(r"^\|\s*`([a-z0-9_]+)`\s*\|(.*)\|\s*$")

# Key prefixes that become <string-array> rather than <string>. Each is a numbered run --
# raag_00.., dbraag_000.., swar_00.. -- and the number is the index the app looks up, so the
# rows have to be complete and in order.
ARRAYS = {
    "raag_names": re.compile(r"^raag_(\d\d)$"),
    "db_raag_names": re.compile(r"^dbraag_(\d\d\d)$"),
    "swar_names": re.compile(r"^swar_(\d\d)$"),
}
SPEC = re.compile(r"%(\d+\$)?[-#+ 0,(]*\d*(?:\.\d+)?[a-zA-Z]")

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/gen_strings.py from translation.md, which is the source of\n"
    "     truth for every user-visible string. Edit the table there, then re-run it. -->\n"
    "<resources>\n"
)


def rows():
    """Every table row, as [key, en, mr, hi]. Raag names are picked out by their key."""
    out = []
    for line in TABLE.read_text().splitlines():
        m = ROW.match(line)
        if not m:
            continue
        cells = [c.strip() for c in m.group(2).split("|")]
        if len(cells) < 3:
            sys.exit(f"row `{m.group(1)}` has {len(cells)} columns, expected at least 4")
        out.append([m.group(1), cells[0], cells[1], cells[2]])
    return out


def escape(s):
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return s.replace("'", "\\'").replace('"', '\\"')


def check(strings):
    """Format specifiers must line up, or the app crashes in a language nobody tested."""
    problems = []
    for key, en, mr, hi in strings:
        want = SPEC.findall(en)
        for lang, value in (("en", en), ("mr", mr), ("hi", hi)):
            got = SPEC.findall(value)
            if len(got) > 1 and not all(got):
                problems.append(f"{key} [{lang}]: {len(got)} args, not all positional: {value}")
            if lang != "en" and got != want:
                problems.append(f"{key} [{lang}]: specifiers {got} against English {want}: {value}")
        if re.search(r"%\d+\$(?![a-zA-Z-#+ 0,(.\d])", en + mr + hi):
            problems.append(f"{key}: a positional argument has no conversion character")
    return problems


def main():
    all_rows = rows()

    arrays = {}
    for name, pattern in ARRAYS.items():
        matched = [(int(pattern.match(r[0]).group(1)), r) for r in all_rows if pattern.match(r[0])]
        matched.sort()
        if [i for i, _ in matched] != list(range(len(matched))):
            print(f"{name}: rows are not a complete run from 0", file=sys.stderr)
            return 1
        arrays[name] = [r for _, r in matched]

    in_array = {id(r) for group in arrays.values() for r in group}
    strings = [r for r in all_rows if id(r) not in in_array]

    problems = check(strings) + check([r for g in arrays.values() for r in g])
    if problems:
        print("refusing to generate:", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 1

    res = ROOT / "app/src/main/res"
    for lang, folder in LOCALES:
        i = COL[lang]
        (res / folder).mkdir(parents=True, exist_ok=True)
        body = "".join(f'    <string name="{r[0]}">{escape(r[i])}</string>\n' for r in strings)
        (res / folder / "strings.xml").write_text(HEADER + body + "</resources>\n")

        blocks = []
        for name, group in arrays.items():
            items = "".join(f"        <item>{escape(r[i])}</item>\n" for r in group)
            blocks.append(
                "    <!-- Index order matters: these are looked up by position, never by\n"
                "         name, so the list must not be re-sorted. -->\n"
                f'    <string-array name="{name}">\n' + items + "    </string-array>\n")
        (res / folder / "arrays.xml").write_text(HEADER + "\n".join(blocks) + "</resources>\n")
        counts = ", ".join(f"{len(g)} {n}" for n, g in arrays.items())
        print(f"{folder}: {len(strings)} strings, {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
