#!/usr/bin/env python3
"""Generate the Android string resources from translation.md.

    python3 tools/gen_strings.py

translation.md is the source of truth for every user-visible string. This reads its tables
and writes values/, values-mr/ and values-hi/ — so a translation is changed by editing the
table and running this, never by editing the XML.

It refuses to write anything if a locale's format specifiers do not match English exactly,
in order. `%1$` with no conversion character sat in the table once and would have crashed
the Result screen at runtime; that check exists because of it.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "translation.md"
LOCALES = (("en", "values"), ("mr", "values-mr"), ("hi", "values-hi"))
COL = {"en": 1, "mr": 2, "hi": 3}

ROW = re.compile(r"^\|\s*`([a-z0-9_]+)`\s*\|(.*)\|\s*$")
SPEC = re.compile(r"%(\d+\$)?[-#+ 0,(]*\d*(?:\.\d+)?[a-zA-Z]")

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/gen_strings.py from translation.md, which is the source of\n"
    "     truth for every user-visible string. Edit the table there, then re-run it. -->\n"
    "<resources>\n"
)


def rows():
    """Every table row, as [key, en, mr, hi]. Raag names are picked out by their key."""
    out = []
    for line in TABLE.read_text().splitlines():
        m = ROW.match(line)
        if not m:
            continue
        cells = [c.strip() for c in m.group(2).split("|")]
        if len(cells) < 3:
            sys.exit(f"row `{m.group(1)}` has {len(cells)} columns, expected at least 4")
        out.append([m.group(1), cells[0], cells[1], cells[2]])
    return out


def escape(s):
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return s.replace("'", "\\'").replace('"', '\\"')


def check(strings):
    """Format specifiers must line up, or the app crashes in a language nobody tested."""
    problems = []
    for key, en, mr, hi in strings:
        want = SPEC.findall(en)
        for lang, value in (("en", en), ("mr", mr), ("hi", hi)):
            got = SPEC.findall(value)
            if len(got) > 1 and not all(got):
                problems.append(f"{key} [{lang}]: {len(got)} args, not all positional: {value}")
            if lang != "en" and got != want:
                problems.append(f"{key} [{lang}]: specifiers {got} against English {want}: {value}")
        if re.search(r"%\d+\$(?![a-zA-Z-#+ 0,(.\d])", en + mr + hi):
            problems.append(f"{key}: a positional argument has no conversion character")
    return problems


def main():
    all_rows = rows()
    raags = [r for r in all_rows if re.fullmatch(r"raag_\d\d", r[0])]
    strings = [r for r in all_rows if r not in raags]

    problems = check(strings)
    if problems:
        print("refusing to generate:", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 1

    expected = sorted(f"raag_{i:02d}" for i in range(len(raags)))
    if [r[0] for r in raags] != expected:
        print(f"raag rows are not raag_00..raag_{len(raags)-1:02d} in order", file=sys.stderr)
        return 1

    res = ROOT / "app/src/main/res"
    for lang, folder in LOCALES:
        i = COL[lang]
        (res / folder).mkdir(parents=True, exist_ok=True)
        body = "".join(f'    <string name="{r[0]}">{escape(r[i])}</string>\n' for r in strings)
        (res / folder / "strings.xml").write_text(HEADER + body + "</resources>\n")

        items = "".join(f"        <item>{escape(r[i])}</item>\n" for r in raags)
        array = (
            '    <!-- raags.json order, which is the order the model emits. Looked up by\n'
            '         index, so this must not be re-sorted. -->\n'
            '    <string-array name="raag_names">\n' + items + "    </string-array>\n"
        )
        (res / folder / "arrays.xml").write_text(HEADER + array + "</resources>\n")
        print(f"{folder}: {len(strings)} strings, {len(raags)} raag names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
